# Generated by Django 6.1.1 on 2026-10-04 18:16

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('masters', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CultivationBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch_number', models.CharField(db_index=True, max_length=50, unique=True)),
                ('start_date', models.DateField()),
                ('expected_harvest_date', models.DateField(blank=True, null=True)),
                ('actual_harvest_date', models.DateField(blank=True, null=True)),
                ('cultivated_quantity', models.DecimalField(decimal_places=3, default=Decimal('0.000'), max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.000'))])),
                ('area', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('status', models.CharField(choices=[('PLANNED', 'Planned'), ('ACTIVE', 'Active'), ('HARVESTED', 'Harvested'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='PLANNED', max_length=20)),
                ('remarks', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cultivation_batches', to=settings.AUTH_USER_MODEL)),
                ('farm_plot', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cultivation_batches', to='masters.farmplot')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cultivation_batches', to='masters.item')),
            ],
            options={
                'verbose_name_plural': 'Cultivation Batches',
                'ordering': ['-start_date', '-id'],
            },
        ),
        migrations.CreateModel(
            name='Harvest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('harvest_number', models.CharField(db_index=True, max_length=50, unique=True)),
                ('harvest_date', models.DateField()),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.001'))])),
                ('unit_cost', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('total_cost', models.DecimalField(decimal_places=2, max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('quality_grade', models.CharField(blank=True, choices=[('GRADE_A', 'Grade A / Premium'), ('GRADE_B', 'Grade B / Standard'), ('GRADE_C', 'Grade C / Economy')], default='GRADE_A', max_length=20)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('POSTED', 'Posted'), ('CANCELLED', 'Cancelled')], default='DRAFT', max_length=20)),
                ('remarks', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('accepted_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='accepted_harvests', to=settings.AUTH_USER_MODEL)),
                ('cultivation_batch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='harvests', to='farming.cultivationbatch')),
            ],
            options={
                'ordering': ['-harvest_date', '-id'],
            },
        ),
        migrations.AddIndex(
            model_name='cultivationbatch',
            index=models.Index(fields=['batch_number'], name='farming_cul_batch_n_0b8a7d_idx'),
        ),
        migrations.AddIndex(
            model_name='cultivationbatch',
            index=models.Index(fields=['status'], name='farming_cul_status_efd54d_idx'),
        ),
        migrations.AddIndex(
            model_name='cultivationbatch',
            index=models.Index(fields=['start_date'], name='farming_cul_start_d_f80f90_idx'),
        ),
        migrations.AddIndex(
            model_name='harvest',
            index=models.Index(fields=['harvest_number'], name='farming_har_harvest_2b28c8_idx'),
        ),
        migrations.AddIndex(
            model_name='harvest',
            index=models.Index(fields=['status'], name='farming_har_status_c8c552_idx'),
        ),
        migrations.AddIndex(
            model_name='harvest',
            index=models.Index(fields=['harvest_date'], name='farming_har_harvest_5236fd_idx'),
        ),
        migrations.AddConstraint(
            model_name='harvest',
            constraint=models.CheckConstraint(condition=models.Q(('quantity__gt', 0)), name='harvest_quantity_gt_zero'),
        ),
    ]
